language: c
script: bash -ex .travis.sh
env:
  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
  # - OCAML_VERSION=3.12.1 OPAM_VERSION=1.0.0
  # - OCAML_VERSION=4.00.1 OPAM_VERSION=1.0.0
  # - OCAML_VERSION=4.01.0 OPAM_VERSION=1.0.0

# notifications:
#   email:
#       - simon.cruanes.2007+travis@m4x.org
#       - add other adresses here (or batteries-devel or something?)
