language: c
script: bash -ex .travis.sh
env:
  - OCAML_VERSION=3.12.1
  - OCAML_VERSION=4.00.1
  - OCAML_VERSION=4.01.0
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.07.0
  - OCAML_VERSION=4.08.0

# notifications:
#   email:
#       - simon.cruanes.2007+travis@m4x.org
#       - add other addresses here (or batteries-devel or something?)
